#define SCREEN_X 300
#define SCREEN_Y 100
#define SCREEN_WIDTH 407
#define SCREEN_HEIGHT 600

#define BALL_RADIUS 8

#define PAD_WIDTH 100
#define PAD_HEIGHT 10
#define KEY_MOVE_STEP 10

#define BRICK_ROWS 3
#define BRICK_COLS 12
#define NUM_BRICKS BRICK_ROWS*BRICK_COLS
#define BRICK_WIDTH 33
#define BRICK_HEIGHT 15

